export type Platform = 'leetcode' | 'codeforces' | 'codechef' | 'gfg';
export type Difficulty = 'Foundation' | 'Pattern Unlocker' | 'Brain Burner';

export interface Problem {
  id: string;
  title: string;
  platform: Platform;
  difficulty: Difficulty;
  tags: string[];
  url: string;
  primaryPatternId: string;
  secondaryPatternIds?: string[];
  insight?: string;
  checklist?: string[];
  solutionUrl?: string;
  discussionUrl?: string;
  acceptanceRate?: number;
  solveCount?: number;
  lastAttemptAt?: number;
  timeSpent?: number;
  benchmarkTime?: number; // Target time for senior developers in minutes
}

export interface Pattern {
  id: string;
  name: string;
  description: string;
  antipatterns?: string[]; // When NOT to use this pattern
  problemCount: number;
  problems: Problem[];
}

export interface MasteryList {
  id: string;
  title: string;
  description: string;
  problemCount: number;
  estimatedDifficulty: string;
  problems: Problem[];
}

export const patterns: Pattern[] = [
  {
    id: 'sliding-window',
    name: 'Sliding Window',
    description: 'The standard for subarray/substring problems where the window slides across the collection.',
    antipatterns: [
      'Avoid if the collection is not contiguous (e.g., subsequences).',
      'Don\'t use if the order of elements doesn\'t matter (e.g., finding if a set contains a value).',
      'Overkill if the answer can be derived from simple global stats (like total sum).'
    ],
    problemCount: 10,
    problems: [
      {
        id: 'sw-1',
        title: 'Maximum Subarray of Size K',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Sliding Window', 'Array'],
        url: 'https://leetcode.com/problems/maximum-average-subarray-i/',
        primaryPatternId: 'sliding-window',
        benchmarkTime: 10,
        insight: 'Use a fixed window to maintain the sum and slide it by adding the next element and removing the first.',
        checklist: [
          'Initialize window sum with the first K elements',
          'Handle array lengths less than K',
          'Maintain a max_sum variable for comparison',
          'Slide the window efficiently by adding/subtracting endpoints'
        ],
        solutionUrl: 'https://leetcode.com/problems/maximum-average-subarray-i/solutions/',
        discussionUrl: 'https://leetcode.com/problems/maximum-average-subarray-i/discussion/',
        acceptanceRate: 45.2,
      },
      {
        id: 'sw-2',
        title: 'Longest Substring Without Repeating Characters',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Sliding Window', 'String', 'Hash Map'],
        url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
        primaryPatternId: 'sliding-window',
        secondaryPatternIds: ['hashing'],
        benchmarkTime: 15,
        insight: 'Use a dynamic window and a hash map to store the last seen index of each character.',
        checklist: [
          'Identify the window boundaries',
          'Use a hash map for O(1) character lookup',
          'Update window start based on duplicate character position',
          'Handle empty or single-character strings'
        ],
        solutionUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/solutions/',
        discussionUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/discussion/',
        acceptanceRate: 34.1,
      },
      {
        id: 'sw-3',
        title: 'Minimum Window Substring',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Sliding Window', 'String', 'Two Pointers'],
        url: 'https://leetcode.com/problems/minimum-window-substring/',
        primaryPatternId: 'sliding-window',
        acceptanceRate: 41.5,
      },
      {
        id: 'sw-4',
        title: 'Permutation in String',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Sliding Window', 'String'],
        url: 'https://leetcode.com/problems/permutation-in-string/',
        primaryPatternId: 'sliding-window',
        acceptanceRate: 44.2,
      },
      {
        id: 'sw-5',
        title: 'Fruit Into Baskets',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Sliding Window', 'Hash Map'],
        url: 'https://leetcode.com/problems/fruit-into-baskets/',
        primaryPatternId: 'sliding-window',
        acceptanceRate: 43.1,
      },
      {
        id: 'sw-6',
        title: 'Subarray Product Less Than K',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Sliding Window', 'Array'],
        url: 'https://leetcode.com/problems/subarray-product-less-than-k/',
        primaryPatternId: 'sliding-window',
        acceptanceRate: 46.8,
      },
      {
        id: 'sw-7',
        title: 'Max Consecutive Ones III',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Sliding Window', 'Array'],
        url: 'https://leetcode.com/problems/max-consecutive-ones-iii/',
        primaryPatternId: 'sliding-window',
        acceptanceRate: 52.4,
      },
      {
        id: 'sw-8',
        title: 'Longest Repeating Character Replacement',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Sliding Window', 'String'],
        url: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
        primaryPatternId: 'sliding-window',
        acceptanceRate: 53.1,
      },
      {
        id: 'sw-9',
        title: 'Minimum Size Subarray Sum',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Sliding Window', 'Array'],
        url: 'https://leetcode.com/problems/minimum-size-subarray-sum/',
        primaryPatternId: 'sliding-window',
        benchmarkTime: 15,
        acceptanceRate: 46.5,
        insight: 'Use a dynamic window that expands until the sum is at least K, then shrinks from the left.',
      },
      {
        id: 'sw-10',
        title: 'Books',
        platform: 'codeforces',
        difficulty: 'Pattern Unlocker',
        tags: ['Sliding Window', 'Two Pointers'],
        url: 'https://codeforces.com/problemset/problem/279/B',
        primaryPatternId: 'sliding-window',
        benchmarkTime: 20,
        acceptanceRate: 42.1,
        insight: 'Find the longest continuous segment of books whose total reading time does not exceed T.',
      },
    ],
  },
  {
    id: 'two-pointers',
    name: 'Two Pointers',
    description: 'Efficiency through pointer manipulation, typically on sorted arrays or linked lists.',
    antipatterns: [
      'Don\'t use on unsorted arrays unless you\'re searching for a specific property (like a palindrome).',
      'Avoid if the problem requires tracking more than two distinct states simultaneously.',
      'Inefficient if a simple hash map lookup could solve it in one pass without sorting.'
    ],
    problemCount: 9,
    problems: [
      {
        id: 'tp-1',
        title: 'Valid Palindrome',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Two Pointers', 'String'],
        url: 'https://leetcode.com/problems/valid-palindrome/',
        primaryPatternId: 'two-pointers',
        benchmarkTime: 8,
        acceptanceRate: 46.2,
      },
      {
        id: 'tp-2',
        title: 'Two Sum II - Input Array Is Sorted',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Two Pointers', 'Array'],
        url: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
        primaryPatternId: 'two-pointers',
        benchmarkTime: 10,
        acceptanceRate: 60.1,
      },
      {
        id: 'tp-3',
        title: 'Container With Most Water',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Two Pointers', 'Array'],
        url: 'https://leetcode.com/problems/container-with-most-water/',
        primaryPatternId: 'two-pointers',
        acceptanceRate: 54.3,
      },
      {
        id: 'tp-4',
        title: '3Sum',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Two Pointers', 'Array'],
        url: 'https://leetcode.com/problems/3sum/',
        primaryPatternId: 'two-pointers',
        acceptanceRate: 34.2,
      },
      {
        id: 'tp-5',
        title: 'Remove Duplicates from Sorted Array',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Two Pointers', 'Array'],
        url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',
        primaryPatternId: 'two-pointers',
        acceptanceRate: 56.1,
      },
      {
        id: 'tp-6',
        title: 'Sereja and Dima',
        platform: 'codeforces',
        difficulty: 'Foundation',
        tags: ['Two Pointers', 'Greedy'],
        url: 'https://codeforces.com/problemset/problem/381/A',
        primaryPatternId: 'two-pointers',
        benchmarkTime: 5,
        acceptanceRate: 85.4,
        insight: 'Two players pick the larger of the two ends of a row of cards.',
      },
      {
        id: 'tp-7',
        title: 'Trapping Rain Water',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Two Pointers', 'Array', 'Stack'],
        url: 'https://leetcode.com/problems/trapping-rain-water/',
        primaryPatternId: 'two-pointers',
        acceptanceRate: 60.1,
      },
      {
        id: 'tp-8',
        title: 'Squares of a Sorted Array',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Two Pointers', 'Array'],
        url: 'https://leetcode.com/problems/squares-of-a-sorted-array/',
        primaryPatternId: 'two-pointers',
        acceptanceRate: 72.1,
      },
      {
        id: 'tp-9',
        title: 'Backspace String Compare',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Two Pointers', 'String'],
        url: 'https://leetcode.com/problems/backspace-string-compare/',
        primaryPatternId: 'two-pointers',
        acceptanceRate: 48.2,
      },
    ],
  },
  {
    id: 'hashing',
    name: 'Hashing',
    description: 'Leverage hash maps for O(1) lookups and fast frequency counting.',
    antipatterns: [
      'Don\'t use if the problem requires elements in a specific order (consider a Balanced BST or sorting).',
      'Inefficient for range-based queries (e.g., "count elements between X and Y").',
      'Beware of space complexity: O(N) space can be a bottleneck in memory-constrained environments.'
    ],
    problemCount: 8,
    problems: [
      {
        id: 'h-1',
        title: 'Two Sum',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Hashing', 'Array'],
        url: 'https://leetcode.com/problems/two-sum/',
        primaryPatternId: 'hashing',
        benchmarkTime: 5,
        acceptanceRate: 50.1,
      },
      {
        id: 'h-2',
        title: 'Contains Duplicate',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Hashing', 'Array'],
        url: 'https://leetcode.com/problems/contains-duplicate/',
        primaryPatternId: 'hashing',
        benchmarkTime: 5,
        acceptanceRate: 61.3,
      },
      {
        id: 'h-3',
        title: 'Valid Anagram',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Hashing', 'String'],
        url: 'https://leetcode.com/problems/valid-anagram/',
        primaryPatternId: 'hashing',
        acceptanceRate: 63.5,
      },
      {
        id: 'h-4',
        title: 'Group Anagrams',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Hashing', 'String', 'Array'],
        url: 'https://leetcode.com/problems/group-anagrams/',
        primaryPatternId: 'hashing',
        acceptanceRate: 66.8,
      },
      {
        id: 'h-5',
        title: 'Longest Consecutive',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Hashing', 'Array'],
        url: 'https://leetcode.com/problems/longest-consecutive/',
        primaryPatternId: 'hashing',
        acceptanceRate: 49.2,
      },
      {
        id: 'h-6',
        title: 'LRU Cache',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Hashing', 'Design', 'LinkedList'],
        url: 'https://leetcode.com/problems/lru-cache/',
        primaryPatternId: 'hashing',
        acceptanceRate: 41.2,
      },
      {
        id: 'h-7',
        title: 'Find All Anagrams in a String',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Hashing', 'Sliding Window', 'String'],
        url: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/',
        primaryPatternId: 'hashing',
        secondaryPatternIds: ['sliding-window'],
        acceptanceRate: 50.1,
      },
      {
        id: 'h-8',
        title: 'Registration system',
        platform: 'codeforces',
        difficulty: 'Pattern Unlocker',
        tags: ['Hashing', 'String'],
        url: 'https://codeforces.com/problemset/problem/4/C',
        primaryPatternId: 'hashing',
        benchmarkTime: 10,
        acceptanceRate: 55.4,
        insight: 'Use a hash map to keep track of the counts of each username and append the count if it already exists.',
      },
    ],
  },
  {
    id: 'binary-search',
    name: 'Binary Search',
    description: 'Master logarithmic time complexity with binary search',
    problemCount: 7,
    problems: [
      {
        id: 'bs-1',
        title: 'Binary Search',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Binary Search', 'Array'],
        url: 'https://leetcode.com/problems/binary-search/',
        primaryPatternId: 'binary-search',
        acceptanceRate: 56.4,
      },
      {
        id: 'bs-2',
        title: 'First Bad Version',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Binary Search'],
        url: 'https://leetcode.com/problems/first-bad-version/',
        primaryPatternId: 'binary-search',
        acceptanceRate: 43.1,
      },
      {
        id: 'bs-3',
        title: 'Search Insert Position',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Binary Search', 'Array'],
        url: 'https://leetcode.com/problems/search-insert-position/',
        primaryPatternId: 'binary-search',
        acceptanceRate: 45.2,
      },
      {
        id: 'bs-4',
        title: 'Find First and Last Position of Element in Sorted Array',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Binary Search', 'Array'],
        url: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/',
        primaryPatternId: 'binary-search',
        acceptanceRate: 42.1,
      },
      {
        id: 'bs-5',
        title: 'Median of Two Sorted Arrays',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Binary Search', 'Array'],
        url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
        primaryPatternId: 'binary-search',
        acceptanceRate: 36.4,
      },
      {
        id: 'bs-6',
        title: 'Interesting Drink',
        platform: 'codeforces',
        difficulty: 'Foundation',
        tags: ['Binary Search', 'Sorting'],
        url: 'https://codeforces.com/problemset/problem/706/B',
        primaryPatternId: 'binary-search',
        benchmarkTime: 10,
        acceptanceRate: 52.3,
        insight: 'Use upper_bound or binary search to find the number of shops with price <= available coins.',
      },
      {
        id: 'bs-7',
        title: 'Magic Powder - 1',
        platform: 'codeforces',
        difficulty: 'Pattern Unlocker',
        tags: ['Binary Search', 'Greedy'],
        url: 'https://codeforces.com/problemset/problem/670/D1',
        primaryPatternId: 'binary-search',
        benchmarkTime: 20,
        acceptanceRate: 48.7,
        insight: 'Binary search on the answer (number of cookies) and check feasibility.',
      },
    ],
  },
  {
    id: 'recursion-backtracking',
    name: 'Recursion & Backtracking',
    description: 'Explore all possibilities with systematic recursion',
    problemCount: 13,
    problems: [
      {
        id: 'rb-1',
        title: 'Climbing Stairs',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Recursion', 'Dynamic Programming'],
        url: 'https://leetcode.com/problems/climbing-stairs/',
        primaryPatternId: 'recursion-backtracking',
        secondaryPatternIds: ['dynamic-programming'],
        acceptanceRate: 52.3,
      },
      {
        id: 'rb-2',
        title: 'Permutations',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Backtracking', 'Array'],
        url: 'https://leetcode.com/problems/permutations/',
        primaryPatternId: 'recursion-backtracking',
        acceptanceRate: 76.4,
      },
      {
        id: 'rb-3',
        title: 'Combinations',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Backtracking', 'Array'],
        url: 'https://leetcode.com/problems/combinations/',
        primaryPatternId: 'recursion-backtracking',
        acceptanceRate: 68.2,
      },
      {
        id: 'rb-4',
        title: 'Letter Combinations of a Phone Number',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Backtracking', 'String'],
        url: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
        primaryPatternId: 'recursion-backtracking',
        acceptanceRate: 59.1,
      },
      {
        id: 'rb-5',
        title: 'Subsets',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Backtracking', 'Array'],
        url: 'https://leetcode.com/problems/subsets/',
        primaryPatternId: 'recursion-backtracking',
        acceptanceRate: 76.2,
      },
      {
        id: 'rb-6',
        title: 'N-Queens',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Backtracking', 'Array'],
        url: 'https://leetcode.com/problems/n-queens/',
        primaryPatternId: 'recursion-backtracking',
        acceptanceRate: 36.8,
      },
      {
        id: 'rb-7',
        title: 'Sudoku Solver',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Backtracking', 'Array'],
        url: 'https://leetcode.com/problems/sudoku-solver/',
        primaryPatternId: 'recursion-backtracking',
        acceptanceRate: 60.1,
      },
      {
        id: 'rb-8',
        title: 'Combination Sum',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Backtracking', 'Array'],
        url: 'https://leetcode.com/problems/combination-sum/',
        primaryPatternId: 'recursion-backtracking',
        benchmarkTime: 15,
        acceptanceRate: 68.4,
        insight: 'Use backtracking with a target sum, ensuring duplicates are avoided by choosing elements from the current index onwards.',
      },
      {
        id: 'rb-9',
        title: 'Word Search',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Backtracking', 'Matrix'],
        url: 'https://leetcode.com/problems/word-search/',
        primaryPatternId: 'recursion-backtracking',
        benchmarkTime: 20,
        acceptanceRate: 40.2,
        insight: 'DFS on each cell to match the word, marking visited cells to avoid reuse.',
      },
      {
        id: 'rb-10',
        title: 'Palindrome Partitioning',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Backtracking', 'String'],
        url: 'https://leetcode.com/problems/palindrome-partitioning/',
        primaryPatternId: 'recursion-backtracking',
        benchmarkTime: 20,
        acceptanceRate: 65.1,
        insight: 'Partition the string into substrings and only continue if the current substring is a palindrome.',
      },
      {
        id: 'rb-11',
        title: 'Rat in a Maze',
        platform: 'gfg',
        difficulty: 'Pattern Unlocker',
        tags: ['Backtracking', 'Matrix'],
        url: 'https://www.geeksforgeeks.org/problems/rat-in-a-maze-problem/1',
        primaryPatternId: 'recursion-backtracking',
        benchmarkTime: 15,
        acceptanceRate: 45.4,
        insight: 'Explore all possible paths from top-left to bottom-right, keeping track of visited cells.',
      },
      {
        id: 'rb-12',
        title: 'Power of Two',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Recursion', 'Math'],
        url: 'https://leetcode.com/problems/power-of-two/',
        primaryPatternId: 'recursion-backtracking',
        benchmarkTime: 5,
        acceptanceRate: 46.5,
      },
      {
        id: 'rb-13',
        title: 'Fibonacci Number',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Recursion', 'Math'],
        url: 'https://leetcode.com/problems/fibonacci-number/',
        primaryPatternId: 'recursion-backtracking',
        benchmarkTime: 5,
        acceptanceRate: 70.2,
      },
    ],
  },
  {
    id: 'dynamic-programming',
    name: 'Dynamic Programming',
    description: 'Break down complex problems into overlapping subproblems',
    problemCount: 13,
    problems: [
      {
        id: 'dp-1',
        title: 'Fibonacci Number',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Dynamic Programming'],
        url: 'https://leetcode.com/problems/fibonacci-number/',
        primaryPatternId: 'dynamic-programming',
        acceptanceRate: 70.2,
      },
      {
        id: 'dp-2',
        title: 'House Robber',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Dynamic Programming', 'Array'],
        url: 'https://leetcode.com/problems/house-robber/',
        primaryPatternId: 'dynamic-programming',
        acceptanceRate: 51.3,
      },
      {
        id: 'dp-3',
        title: 'Coin Change',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Dynamic Programming', 'Array'],
        url: 'https://leetcode.com/problems/coin-change/',
        primaryPatternId: 'dynamic-programming',
        acceptanceRate: 43.5,
      },
      {
        id: 'dp-4',
        title: 'Longest Increasing Subsequence',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Dynamic Programming', 'Array'],
        url: 'https://leetcode.com/problems/longest-increasing-subsequence/',
        primaryPatternId: 'dynamic-programming',
        acceptanceRate: 54.1,
      },
      {
        id: 'dp-5',
        title: 'Edit Distance',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Dynamic Programming', 'String'],
        url: 'https://leetcode.com/problems/edit-distance/',
        primaryPatternId: 'dynamic-programming',
        acceptanceRate: 56.4,
      },
      {
        id: 'dp-6',
        title: '0/1 Knapsack',
        platform: 'codeforces',
        difficulty: 'Pattern Unlocker',
        tags: ['Dynamic Programming'],
        url: 'https://www.codeforces.com/',
        primaryPatternId: 'dynamic-programming',
        acceptanceRate: 40.1,
      },
      {
        id: 'dp-7',
        title: 'Maximum Subarray',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Dynamic Programming', 'Array'],
        url: 'https://leetcode.com/problems/maximum-subarray/',
        primaryPatternId: 'dynamic-programming',
        acceptanceRate: 50.3,
      },
      {
        id: 'dp-8',
        title: 'Burst Balloons',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Dynamic Programming', 'Array'],
        url: 'https://leetcode.com/problems/burst-balloons/',
        primaryPatternId: 'dynamic-programming',
        acceptanceRate: 58.2,
      },
      {
        id: 'dp-9',
        title: 'Cut Ribbon',
        platform: 'codeforces',
        difficulty: 'Foundation',
        tags: ['Dynamic Programming'],
        url: 'https://codeforces.com/problemset/problem/189/A',
        primaryPatternId: 'dynamic-programming',
        benchmarkTime: 15,
        acceptanceRate: 45.2,
        insight: 'Find the maximum number of pieces the ribbon can be cut into given allowed lengths.',
      },
      {
        id: 'dp-10',
        title: 'Boredom',
        platform: 'codeforces',
        difficulty: 'Pattern Unlocker',
        tags: ['Dynamic Programming'],
        url: 'https://codeforces.com/problemset/problem/455/A',
        primaryPatternId: 'dynamic-programming',
        benchmarkTime: 20,
        acceptanceRate: 38.4,
        insight: 'Transform the input into counts and use a DP approach similar to House Robber.',
      },
      {
        id: 'dp-11',
        title: 'Word Break',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Dynamic Programming', 'String'],
        url: 'https://leetcode.com/problems/word-break/',
        primaryPatternId: 'dynamic-programming',
        benchmarkTime: 20,
        acceptanceRate: 46.8,
        insight: 'Determine if the string can be segmented into a space-separated sequence of one or more dictionary words.',
      },
      {
        id: 'dp-12',
        title: 'Super Egg Drop',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Dynamic Programming', 'Binary Search', 'Math'],
        url: 'https://leetcode.com/problems/super-egg-drop/',
        primaryPatternId: 'dynamic-programming',
        benchmarkTime: 30,
        acceptanceRate: 27.5,
        insight: 'Use DP with binary search optimization to find the minimum moves required.',
      },
      {
        id: 'dp-13',
        title: 'Matrix Chain Multiplication',
        platform: 'gfg',
        difficulty: 'Brain Burner',
        tags: ['Dynamic Programming', 'Matrix'],
        url: 'https://www.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1',
        primaryPatternId: 'dynamic-programming',
        benchmarkTime: 25,
        acceptanceRate: 45.2,
        insight: 'Find the most efficient way to multiply a given sequence of matrices.',
      },
    ],
  },
  {
    id: 'graphs',
    name: 'Graphs',
    description: 'Navigate complex networks with traversal and algorithms',
    problemCount: 14,
    problems: [
      {
        id: 'g-1',
        title: 'Number of Islands',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Graph', 'DFS', 'BFS'],
        url: 'https://leetcode.com/problems/number-of-islands/',
        primaryPatternId: 'graphs',
        acceptanceRate: 59.4,
      },
      {
        id: 'g-2',
        title: 'Clone Graph',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Graph', 'DFS', 'BFS'],
        url: 'https://leetcode.com/problems/clone-graph/',
        primaryPatternId: 'graphs',
        acceptanceRate: 54.2,
      },
      {
        id: 'g-3',
        title: 'Course Schedule',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Graph', 'Topological Sort'],
        url: 'https://leetcode.com/problems/course-schedule/',
        primaryPatternId: 'graphs',
        acceptanceRate: 56.8,
      },
      {
        id: 'g-4',
        title: 'Alien Dictionary',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Graph', 'Topological Sort'],
        url: 'https://leetcode.com/problems/alien-dictionary/',
        primaryPatternId: 'graphs',
        acceptanceRate: 35.1,
      },
      {
        id: 'g-5',
        title: 'Shortest Path in a Grid with Obstacles Elimination',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Graph', 'BFS'],
        url: 'https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/',
        primaryPatternId: 'graphs',
        acceptanceRate: 46.2,
      },
      {
        id: 'g-6',
        title: 'Path Sum II',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Graph', 'DFS', 'Tree'],
        url: 'https://leetcode.com/problems/path-sum-ii/',
        primaryPatternId: 'graphs',
        acceptanceRate: 56.4,
      },
      {
        id: 'g-7',
        title: 'Word Ladder',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Graph', 'BFS'],
        url: 'https://leetcode.com/problems/word-ladder/',
        primaryPatternId: 'graphs',
        acceptanceRate: 38.2,
      },
      {
        id: 'g-8',
        title: 'Network Delay Time',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Graph', 'Dijkstra'],
        url: 'https://leetcode.com/problems/network-delay-time/',
        primaryPatternId: 'graphs',
        acceptanceRate: 54.1,
      },
      {
        id: 'g-9',
        title: 'Min Cost to Connect All Points',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Graph', 'MST', 'Prim\'s', 'Kruskal\'s'],
        url: 'https://leetcode.com/problems/min-cost-to-connect-all-points/',
        primaryPatternId: 'graphs',
        benchmarkTime: 25,
        acceptanceRate: 64.2,
        insight: 'Find the Minimum Spanning Tree of a coordinate-based graph.',
      },
      {
        id: 'g-10',
        title: 'Cheapest Flights Within K Stops',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Graph', 'Bellman-Ford', 'Dijkstra'],
        url: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
        primaryPatternId: 'graphs',
        benchmarkTime: 20,
        acceptanceRate: 38.4,
        insight: 'Find the shortest path with a constraint on the number of edges.',
      },
      {
        id: 'g-11',
        title: 'Smallest Neighbors at Distance Threshold',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Graph', 'Floyd-Warshall'],
        url: 'https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/',
        primaryPatternId: 'graphs',
        benchmarkTime: 20,
        acceptanceRate: 55.1,
        insight: 'Compute all-pairs shortest paths using Floyd-Warshall or N-Dijkstras.',
      },
      {
        id: 'g-12',
        title: 'Course Schedule II',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Graph', 'Topological Sort'],
        url: 'https://leetcode.com/problems/course-schedule-ii/',
        primaryPatternId: 'graphs',
        benchmarkTime: 15,
        acceptanceRate: 52.3,
        insight: 'Return the ordering of courses using Kahn\'s Algorithm or DFS-based topological sort.',
      },
      {
        id: 'g-13',
        title: 'Is Graph Bipartite?',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Graph', 'BFS', 'DFS'],
        url: 'https://leetcode.com/problems/is-graph-bipartite/',
        primaryPatternId: 'graphs',
        benchmarkTime: 12,
        acceptanceRate: 54.1,
        insight: 'Check if the graph can be 2-colored such that no two adjacent nodes have the same color.',
      },
      {
        id: 'g-14',
        title: 'Strongly Connected Components',
        platform: 'gfg',
        difficulty: 'Brain Burner',
        tags: ['Graph', 'SCC', 'Kosaraju'],
        url: 'https://www.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1',
        primaryPatternId: 'graphs',
        benchmarkTime: 25,
        acceptanceRate: 45.2,
        insight: 'Use Kosaraju\'s or Tarjan\'s algorithm to find components where every vertex is reachable from every other vertex.',
      },
    ],
  },
  {
    id: 'greedy',
    name: 'Greedy',
    description: 'Make optimal local choices that lead to global solutions',
    problemCount: 6,
    problems: [
      {
        id: 'gr-1',
        title: 'Jump Game',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Greedy', 'Array'],
        url: 'https://leetcode.com/problems/jump-game/',
        primaryPatternId: 'greedy',
        acceptanceRate: 40.1,
      },
      {
        id: 'gr-2',
        title: 'Jump Game II',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Greedy', 'Array'],
        url: 'https://leetcode.com/problems/jump-game-ii/',
        primaryPatternId: 'greedy',
        acceptanceRate: 41.2,
      },
      {
        id: 'gr-3',
        title: 'Gas Station',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Greedy', 'Array'],
        url: 'https://leetcode.com/problems/gas-station/',
        primaryPatternId: 'greedy',
        acceptanceRate: 46.4,
      },
      {
        id: 'gr-4',
        title: 'Interval Scheduling Maximization',
        platform: 'codeforces',
        difficulty: 'Pattern Unlocker',
        tags: ['Greedy'],
        url: 'https://www.codeforces.com/',
        primaryPatternId: 'greedy',
        acceptanceRate: 35.2,
      },
      {
        id: 'gr-5',
        title: 'Minimum Number of Arrows to Burst Balloons',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Greedy', 'Interval'],
        url: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/',
        primaryPatternId: 'greedy',
        acceptanceRate: 56.4,
      },
      {
        id: 'gr-6',
        title: 'Reconstructing Sequence',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Greedy', 'Topological Sort'],
        url: 'https://leetcode.com/problems/sequence-reconstruction/',
        primaryPatternId: 'greedy',
        acceptanceRate: 29.8,
      },
    ],
  },
  {
    id: 'linked-lists',
    name: 'Linked Lists',
    description: 'Linear data structures with pointers, including single, double, and circular lists.',
    antipatterns: [
      'Avoid if frequent random access is required (use arrays instead).',
      'Inefficient for problems with low memory overhead requirements.',
      'Check if a simple array/stack could handle the problem with less complexity.'
    ],
    problemCount: 11,
    problems: [
      {
        id: 'll-1',
        title: 'Reverse Linked List',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Linked List'],
        url: 'https://leetcode.com/problems/reverse-linked-list/',
        primaryPatternId: 'linked-lists',
        benchmarkTime: 10,
        acceptanceRate: 75.1,
        insight: 'Use a simple iterative approach with three pointers: prev, current, and next.',
      },
      {
        id: 'll-2',
        title: 'Linked List Cycle',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Linked List', 'Two Pointers'],
        url: 'https://leetcode.com/problems/linked-list-cycle/',
        primaryPatternId: 'linked-lists',
        secondaryPatternIds: ['two-pointers'],
        benchmarkTime: 12,
        acceptanceRate: 48.2,
        insight: 'Use Floyd\'s Cycle-Finding Algorithm (slow and fast pointers).',
      },
      {
        id: 'll-3',
        title: 'Merge Two Sorted Lists',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Linked List', 'Recursion'],
        url: 'https://leetcode.com/problems/merge-two-sorted-lists/',
        primaryPatternId: 'linked-lists',
        secondaryPatternIds: ['recursion-backtracking'],
        benchmarkTime: 10,
        acceptanceRate: 63.5,
        insight: 'Use a dummy node to simplify the head management while merging.',
      },
      {
        id: 'll-4',
        title: 'Remove Nth Node From End of List',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Linked List', 'Two Pointers'],
        url: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
        primaryPatternId: 'linked-lists',
        secondaryPatternIds: ['two-pointers'],
        benchmarkTime: 15,
        acceptanceRate: 43.1,
        insight: 'Use two pointers separated by N steps to find the node before the target.',
      },
      {
        id: 'll-5',
        title: 'Copy List with Random Pointer',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Linked List', 'Hash Map'],
        url: 'https://leetcode.com/problems/copy-list-with-random-pointer/',
        primaryPatternId: 'linked-lists',
        secondaryPatternIds: ['hashing'],
        benchmarkTime: 25,
        acceptanceRate: 54.2,
        insight: 'Use a hash map to map original nodes to their copies, or insert copies between original nodes.',
      },
      {
        id: 'll-6',
        title: 'Add Two Numbers',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Linked List', 'Math'],
        url: 'https://leetcode.com/problems/add-two-numbers/',
        primaryPatternId: 'linked-lists',
        benchmarkTime: 15,
        acceptanceRate: 41.2,
        insight: 'Iterate through both lists, maintaining a carry for the sum of digits.',
      },
      {
        id: 'll-7',
        title: 'Middle of the Linked List',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Linked List', 'Two Pointers'],
        url: 'https://leetcode.com/problems/middle-of-the-linked-list/',
        primaryPatternId: 'linked-lists',
        benchmarkTime: 5,
        acceptanceRate: 76.4,
        insight: 'Use fast and slow pointers; fast moves twice as fast as slow.',
      },
      {
        id: 'll-8',
        title: 'Rotate List',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Linked List', 'Two Pointers'],
        url: 'https://leetcode.com/problems/rotate-list/',
        primaryPatternId: 'linked-lists',
        benchmarkTime: 15,
        acceptanceRate: 36.5,
        insight: 'Connect the tail to the head to form a circle, then break at the new tail.',
      },
      {
        id: 'll-9',
        title: 'Swap Nodes in Pairs',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Linked List', 'Recursion'],
        url: 'https://leetcode.com/problems/swap-nodes-in-pairs/',
        primaryPatternId: 'linked-lists',
        benchmarkTime: 12,
        acceptanceRate: 53.1,
        insight: 'Can be solved iteratively with a dummy node or recursively.',
      },
      {
        id: 'll-10',
        title: 'Intersection of Two Linked Lists',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Linked List', 'Two Pointers'],
        url: 'https://leetcode.com/problems/intersection-of-two-linked-lists/',
        primaryPatternId: 'linked-lists',
        benchmarkTime: 15,
        acceptanceRate: 56.4,
        insight: 'Align the heads of both lists by calculating lengths or use two-pointer cycle trick.',
      },
      {
        id: 'll-11',
        title: 'Reorder List',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Linked List', 'Two Pointers', 'Stack'],
        url: 'https://leetcode.com/problems/reorder-list/',
        primaryPatternId: 'linked-lists',
        benchmarkTime: 20,
        acceptanceRate: 55.2,
        insight: 'Find the middle, reverse the second half, then merge them alternatingly.',
      },
    ],
  },
  {
    id: 'stacks-queues',
    name: 'Stacks and Queues',
    description: 'LIFO and FIFO data structures for systematic processing and evaluation.',
    antipatterns: [
      'Don\'t use a stack for search problems unless it\'s DFS.',
      'Avoid if the order of processing doesn\'t follow FIFO/LIFO.',
      'Be careful with memory limits when using recursion (internal stack).'
    ],
    problemCount: 8,
    problems: [
      {
        id: 'sq-1',
        title: 'Valid Parentheses',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Stack', 'String'],
        url: 'https://leetcode.com/problems/valid-parentheses/',
        primaryPatternId: 'stacks-queues',
        benchmarkTime: 5,
        acceptanceRate: 40.5,
        insight: 'Use a stack to match opening and closing brackets in order.',
      },
      {
        id: 'sq-2',
        title: 'Implement Queue using Stacks',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Stack', 'Design'],
        url: 'https://leetcode.com/problems/implement-queue-using-stacks/',
        primaryPatternId: 'stacks-queues',
        benchmarkTime: 10,
        acceptanceRate: 63.1,
        insight: 'Use two stacks: one for pushing elements and one for popping/peeking.',
      },
      {
        id: 'sq-3',
        title: 'Min Stack',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Stack', 'Design'],
        url: 'https://leetcode.com/problems/min-stack/',
        primaryPatternId: 'stacks-queues',
        benchmarkTime: 12,
        acceptanceRate: 53.4,
        insight: 'Use an auxiliary stack to store the minimum value at each state of the main stack.',
      },
      {
        id: 'sq-4',
        title: 'Evaluate Reverse Polish Notation',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Stack', 'Math'],
        url: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
        primaryPatternId: 'stacks-queues',
        benchmarkTime: 15,
        acceptanceRate: 47.2,
        insight: 'Iterate through tokens, pushing numbers onto the stack and popping for operations.',
      },
      {
        id: 'sq-5',
        title: 'Sliding Window Maximum',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Stack', 'Deque', 'Sliding Window'],
        url: 'https://leetcode.com/problems/sliding-window-maximum/',
        primaryPatternId: 'stacks-queues',
        secondaryPatternIds: ['sliding-window'],
        benchmarkTime: 25,
        acceptanceRate: 46.5,
         insight: 'Use a deque to store indices of potential maximums in a monotonic decreasing order.',
      },
      {
        id: 'sq-6',
        title: 'Queue at the School',
        platform: 'codeforces',
        difficulty: 'Foundation',
        tags: ['Queue', 'Simulation'],
        url: 'https://codeforces.com/problemset/problem/266/B',
        primaryPatternId: 'stacks-queues',
        benchmarkTime: 8,
        acceptanceRate: 85.1,
        insight: 'Simulate the process of swapping students over time steps.',
      },
      {
        id: 'sq-7',
        title: 'Next Greater Element I',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Stack', 'Array'],
        url: 'https://leetcode.com/problems/next-greater-element-i/',
        primaryPatternId: 'stacks-queues',
        benchmarkTime: 10,
        acceptanceRate: 72.1,
        insight: 'Use a monotonic stack to find the next greater element for each number.',
      },
      {
        id: 'sq-8',
        title: 'Largest Rectangle in Histogram',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Stack', 'Array'],
        url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
        primaryPatternId: 'stacks-queues',
        benchmarkTime: 25,
        acceptanceRate: 44.5,
        insight: 'Use a monotonic increasing stack to store heights and calculate area when a smaller height is encountered.',
      },
    ],
  },
  {
    id: 'trees-heaps',
    name: 'Trees and Heaps',
    description: 'Hierarchical data structures for efficient search, priority, and prefix matching.',
    antipatterns: [
      'Avoid BST if the data is already sorted (can lead to unbalanced trees).',
      'Don\'t use a Trie for small fixed-size dictionaries.',
      'Check if a simple hash map could replace a BST for simple O(1) lookups.'
    ],
    problemCount: 10,
    problems: [
      {
        id: 'th-1',
        title: 'Binary Tree Inorder Traversal',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Tree', 'DFS'],
        url: 'https://leetcode.com/problems/binary-tree-inorder-traversal/',
        primaryPatternId: 'trees-heaps',
        benchmarkTime: 8,
        acceptanceRate: 75.4,
        insight: 'Can be solved recursively or iteratively using a stack.',
      },
      {
        id: 'th-2',
        title: 'Maximum Depth of Binary Tree',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Tree', 'DFS'],
        url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
        primaryPatternId: 'trees-heaps',
        benchmarkTime: 5,
        acceptanceRate: 74.2,
        insight: 'Simple recursive approach: max(depth(left), depth(right)) + 1.',
      },
      {
        id: 'th-3',
        title: 'Validate Binary Search Tree',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Tree', 'DFS', 'BST'],
        url: 'https://leetcode.com/problems/validate-binary-search-tree/',
        primaryPatternId: 'trees-heaps',
        benchmarkTime: 15,
        acceptanceRate: 32.5,
        insight: 'Keep track of valid ranges (min, max) for each node as you traverse.',
      },
      {
        id: 'th-4',
        title: 'Kth Largest Element in an Array',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Heap', 'Divide and Conquer'],
        url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
        primaryPatternId: 'trees-heaps',
        benchmarkTime: 12,
        acceptanceRate: 66.4,
        insight: 'Use a min-heap of size K or QuickSelect for optimal performance.',
      },
      {
        id: 'th-5',
        title: 'Implement Trie (Prefix Tree)',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Trie', 'Design'],
        url: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
        primaryPatternId: 'trees-heaps',
        benchmarkTime: 18,
        acceptanceRate: 63.1,
        insight: 'Each node stores children nodes in an array or map for fast character lookup.',
      },
      {
        id: 'th-6',
        title: 'Tree Queries',
        platform: 'codeforces',
        difficulty: 'Brain Burner',
        tags: ['Tree', 'DFS', 'LCA'],
        url: 'https://codeforces.com/problemset/problem/1328/E',
        primaryPatternId: 'trees-heaps',
        benchmarkTime: 30,
        acceptanceRate: 45.2,
        insight: 'Use DFS order and parent nodes to check if paths lie within subtree constraints.',
      },
      {
        id: 'th-7',
        title: 'Path Sum',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Tree', 'DFS'],
        url: 'https://leetcode.com/problems/path-sum/',
        primaryPatternId: 'trees-heaps',
        benchmarkTime: 8,
        acceptanceRate: 50.1,
      },
      {
        id: 'th-8',
        title: 'Kth Smallest Element in a BST',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Tree', 'BST', 'DFS'],
        url: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
        primaryPatternId: 'trees-heaps',
        benchmarkTime: 12,
        acceptanceRate: 72.1,
        insight: 'Inorder traversal of a BST visits nodes in ascending order.',
      },
      {
        id: 'th-9',
        title: 'Same Tree',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Tree', 'DFS'],
        url: 'https://leetcode.com/problems/same-tree/',
        primaryPatternId: 'trees-heaps',
        benchmarkTime: 5,
        acceptanceRate: 61.2,
        insight: 'Compare root values and recursively check left and right subtrees.',
      },
      {
        id: 'th-10',
        title: 'Merge k Sorted Lists',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Heap', 'Linked List', 'Divide and Conquer'],
        url: 'https://leetcode.com/problems/merge-k-sorted-lists/',
        primaryPatternId: 'trees-heaps',
        secondaryPatternIds: ['linked-lists'],
        benchmarkTime: 25,
        acceptanceRate: 53.4,
        insight: 'Use a min-heap to keep track of the smallest current element across all k lists.',
      },
    ],
  },
  {
    id: 'sorting',
    name: 'Sorting',
    description: 'Mastering various sorting techniques and their optimal applications.',
    antipatterns: [
      'Don\'t implement sorting manually unless specifically asked (use built-in sort).',
      'Avoid O(N^2) sorts for large datasets.',
      'Be mindful of stability if the original relative order matters.'
    ],
    problemCount: 5,
    problems: [
      {
        id: 's-1',
        title: 'Sort Colors',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Sorting', 'Two Pointers', 'Array'],
        url: 'https://leetcode.com/problems/sort-colors/',
        primaryPatternId: 'sorting',
        secondaryPatternIds: ['two-pointers'],
        benchmarkTime: 10,
        acceptanceRate: 60.1,
        insight: 'Use the Dutch National Flag algorithm to sort 0s, 1s, and 2s in one pass.',
      },
      {
        id: 's-2',
        title: 'Merge Intervals',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Sorting', 'Array'],
        url: 'https://leetcode.com/problems/merge-intervals/',
        primaryPatternId: 'sorting',
        benchmarkTime: 15,
        acceptanceRate: 46.5,
        insight: 'Sort intervals by start time and merge overlapping ones sequentially.',
      },
      {
        id: 's-3',
        title: 'K Closest Points to Origin',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Sorting', 'Heap', 'Geometry'],
        url: 'https://leetcode.com/problems/k-closest-points-to-origin/',
        primaryPatternId: 'sorting',
        secondaryPatternIds: ['trees-heaps'],
        benchmarkTime: 15,
        acceptanceRate: 66.1,
        insight: 'Can be solved using custom sort or a max-heap of size K.',
      },
      {
        id: 's-4',
        title: 'Dragons',
        platform: 'codeforces',
        difficulty: 'Foundation',
        tags: ['Sorting', 'Greedy'],
        url: 'https://codeforces.com/problemset/problem/230/A',
        primaryPatternId: 'sorting',
        secondaryPatternIds: ['greedy'],
        benchmarkTime: 10,
        acceptanceRate: 75.4,
        insight: 'Sort dragons by their strength to defeat them optimally.',
      },
      {
        id: 's-5',
        title: 'Largest Number',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Sorting', 'String', 'Custom Comparator'],
        url: 'https://leetcode.com/problems/largest-number/',
        primaryPatternId: 'sorting',
        benchmarkTime: 15,
        acceptanceRate: 35.2,
        insight: 'Sort numbers using a custom comparator: a+b > b+a.',
      },
    ],
  },
  {
    id: 'matrices',
    name: 'Matrices',
    description: 'Techniques for navigating and manipulating 2D grids and matrices.',
    antipatterns: [
      'Avoid recursion for grid traversals if the grid is very large (risk of stack overflow).',
      'Be careful with index out of bounds errors in nested loops.',
      'Check if the problem can be simplified by treating rows/columns as sets.'
    ],
    problemCount: 4,
    problems: [
      {
        id: 'm-1',
        title: 'Spiral Matrix',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Matrix', 'Simulation'],
        url: 'https://leetcode.com/problems/spiral-matrix/',
        primaryPatternId: 'matrices',
        benchmarkTime: 15,
        acceptanceRate: 48.1,
        insight: 'Maintain boundaries (top, bottom, left, right) and shrink them as you traverse.',
      },
      {
        id: 'm-2',
        title: 'Rotate Image',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Matrix', 'Math'],
        url: 'https://leetcode.com/problems/rotate-image/',
        primaryPatternId: 'matrices',
        benchmarkTime: 15,
        acceptanceRate: 72.4,
        insight: 'Rotate by transposing the matrix and then reversing each row.',
      },
      {
        id: 'm-3',
        title: 'Set Matrix Zeroes',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Matrix', 'Hash Map'],
        url: 'https://leetcode.com/problems/set-matrix-zeroes/',
        primaryPatternId: 'matrices',
        benchmarkTime: 15,
        acceptanceRate: 53.1,
        insight: 'Use the first row and column as flags to mark rows/columns for zeroing.',
      },
      {
        id: 'm-4',
        title: 'Game of Life',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Matrix', 'Simulation'],
        url: 'https://leetcode.com/problems/game-of-life/',
        primaryPatternId: 'matrices',
        benchmarkTime: 20,
        acceptanceRate: 71.2,
        insight: 'Use temporary states (bit manipulation) to update the matrix in-place.',
      },
    ],
  },
  {
    id: 'array-techniques',
    name: 'Array Techniques',
    description: 'Fundamental array manipulation techniques including rotation, majority voting, and prefix/suffix products.',
    antipatterns: [
      'Don\'t use complex O(N) space solutions if O(1) space is possible.',
      'Avoid nested loops if a single pass or sorting can solve it.',
      'Be mindful of overflow when calculating sums or products.'
    ],
    problemCount: 8,
    problems: [
      {
        id: 'at-1',
        title: 'Rotate Array',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Array', 'Math'],
        url: 'https://leetcode.com/problems/rotate-array/',
        primaryPatternId: 'array-techniques',
        benchmarkTime: 15,
        acceptanceRate: 39.4,
        insight: 'Reverse the whole array, then reverse the first k, then the rest.',
      },
      {
        id: 'at-2',
        title: 'Majority Element',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Array', 'Math'],
        url: 'https://leetcode.com/problems/majority-element/',
        primaryPatternId: 'array-techniques',
        benchmarkTime: 10,
        acceptanceRate: 64.2,
        insight: 'Use Boyer-Moore Voting Algorithm for O(1) space.',
      },
      {
        id: 'at-3',
        title: 'Product of Array Except Self',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Array', 'Prefix Sum'],
        url: 'https://leetcode.com/problems/product-of-array-except-self/',
        primaryPatternId: 'array-techniques',
        benchmarkTime: 15,
        acceptanceRate: 65.1,
        insight: 'Use prefix and suffix products to calculate the result without division.',
      },
      {
        id: 'at-4',
        title: 'Pascal\'s Triangle',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Array', 'Dynamic Programming'],
        url: 'https://leetcode.com/problems/pascals-triangle/',
        primaryPatternId: 'array-techniques',
        benchmarkTime: 10,
        acceptanceRate: 72.4,
        insight: 'Each element is the sum of the two elements directly above it.',
      },
      {
        id: 'at-5',
        title: 'Merge Sorted Array',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Array', 'Two Pointers'],
        url: 'https://leetcode.com/problems/merge-sorted-array/',
        primaryPatternId: 'array-techniques',
        benchmarkTime: 10,
        acceptanceRate: 48.2,
        insight: 'Fill from the back of the first array to avoid extra space.',
      },
      {
        id: 'at-6',
        title: 'Leaders in an array',
        platform: 'gfg',
        difficulty: 'Foundation',
        tags: ['Array'],
        url: 'https://www.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1',
        primaryPatternId: 'array-techniques',
        benchmarkTime: 10,
        acceptanceRate: 65.4,
        insight: 'Traverse from right to left, keeping track of the current maximum.',
      },
      {
        id: 'at-7',
        title: 'Count Negative Numbers in a Sorted Matrix',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Array', 'Binary Search', 'Matrix'],
        url: 'https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/',
        primaryPatternId: 'array-techniques',
        benchmarkTime: 10,
        acceptanceRate: 75.1,
        insight: 'Search from the top-right corner to count negatives in O(M+N).',
      },
      {
        id: 'at-8',
        title: 'Divide Two Integers',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Math', 'Bit Manipulation'],
        url: 'https://leetcode.com/problems/divide-two-integers/',
        primaryPatternId: 'array-techniques',
        benchmarkTime: 20,
        acceptanceRate: 17.5,
        insight: 'Use bit shifting to simulate multiplication by powers of 2 for division.',
      },
    ],
  },
  {
    id: 'string-algorithms',
    name: 'String Algorithms',
    description: 'Essential string manipulation, pattern matching, and transformation techniques.',
    antipatterns: [
      'Avoid frequent string concatenations in loops (use StringBuilder-like patterns).',
      'Don\'t use regex for simple character-based searches.',
      'Check if a simple sliding window or two pointers can solve the problem.'
    ],
    problemCount: 8,
    problems: [
      {
        id: 'sa-1',
        title: 'Reverse Words in a String',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['String', 'Two Pointers'],
        url: 'https://leetcode.com/problems/reverse-words-in-a-string/',
        primaryPatternId: 'string-algorithms',
        benchmarkTime: 12,
        acceptanceRate: 40.1,
        insight: 'Reverse the whole string, then reverse each word, or use a stack.',
      },
      {
        id: 'sa-2',
        title: 'First Unique Character in a String',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['String', 'Hash Map'],
        url: 'https://leetcode.com/problems/first-unique-character-in-a-string/',
        primaryPatternId: 'string-algorithms',
        benchmarkTime: 5,
        acceptanceRate: 61.2,
        insight: 'Use a frequency map to count occurrences and then find the first character with count 1.',
      },
      {
        id: 'sa-3',
        title: 'Integer to Roman',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['String', 'Math'],
        url: 'https://leetcode.com/problems/integer-to-roman/',
        primaryPatternId: 'string-algorithms',
        benchmarkTime: 15,
        acceptanceRate: 64.5,
        insight: 'Map Roman values to their symbols and greedily subtract the largest possible values.',
      },
      {
        id: 'sa-4',
        title: 'Longest Palindromic Substring',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['String', 'Dynamic Programming'],
        url: 'https://leetcode.com/problems/longest-palindromic-substring/',
        primaryPatternId: 'string-algorithms',
        benchmarkTime: 15,
        acceptanceRate: 34.2,
        insight: 'Expand from the center for each character or use DP/Manacher\'s Algorithm.',
      },
      {
        id: 'sa-5',
        title: 'String to Integer (atoi)',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['String', 'Math'],
        url: 'https://leetcode.com/problems/string-to-integer-atoi/',
        primaryPatternId: 'string-algorithms',
        benchmarkTime: 15,
        acceptanceRate: 17.1,
        insight: 'Handle whitespace, signs, and overflow carefully during conversion.',
      },
      {
        id: 'sa-6',
        title: 'Longest Common Prefix',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['String'],
        url: 'https://leetcode.com/problems/longest-common-prefix/',
        primaryPatternId: 'string-algorithms',
        benchmarkTime: 10,
        acceptanceRate: 42.1,
        insight: 'Compare characters index by index across all strings or use vertical scanning.',
      },
      {
        id: 'sa-7',
        title: 'Rotate String',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['String'],
        url: 'https://leetcode.com/problems/rotate-string/',
        primaryPatternId: 'string-algorithms',
        benchmarkTime: 5,
        acceptanceRate: 58.4,
        insight: 'Check if string B is a substring of A + A.',
      },
      {
        id: 'sa-8',
        title: 'Zigzag Conversion',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['String'],
        url: 'https://leetcode.com/problems/zigzag-conversion/',
        primaryPatternId: 'string-algorithms',
        benchmarkTime: 15,
        acceptanceRate: 47.5,
        insight: 'Use rows to store characters and change direction when hitting the top/bottom boundary.',
      },
    ],
  },
  {
    id: 'bit-manipulation',
    name: 'Bit Manipulation',
    description: 'Optimize space and time by manipulating individual bits of data.',
    antipatterns: [
      'Avoid if the logic becomes too obscure for team maintenance.',
      'Don\'t use for simple arithmetic that compilers already optimize.',
      'Beware of language-specific behavior for signed/unsigned shifts.'
    ],
    problemCount: 8,
    problems: [
      {
        id: 'bm-1',
        title: 'Single Number',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Bit Manipulation', 'Array'],
        url: 'https://leetcode.com/problems/single-number/',
        primaryPatternId: 'bit-manipulation',
        benchmarkTime: 5,
        acceptanceRate: 72.1,
        insight: 'Use XOR: A ^ A = 0 and A ^ 0 = A. All duplicates cancel out.',
      },
      {
        id: 'bm-2',
        title: 'Number of 1 Bits',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Bit Manipulation'],
        url: 'https://leetcode.com/problems/number-of-1-bits/',
        primaryPatternId: 'bit-manipulation',
        benchmarkTime: 5,
        acceptanceRate: 68.4,
        insight: 'Use n & (n - 1) to clear the least significant set bit repeatedly.',
      },
      {
        id: 'bm-3',
        title: 'Counting Bits',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Bit Manipulation', 'Dynamic Programming'],
        url: 'https://leetcode.com/problems/counting-bits/',
        primaryPatternId: 'bit-manipulation',
        secondaryPatternIds: ['dynamic-programming'],
        benchmarkTime: 10,
        acceptanceRate: 77.2,
        insight: 'Use DP: bits[i] = bits[i >> 1] + (i & 1).',
      },
      {
        id: 'bm-4',
        title: 'Reverse Bits',
        platform: 'leetcode',
        difficulty: 'Pattern Unlocker',
        tags: ['Bit Manipulation'],
        url: 'https://leetcode.com/problems/reverse-bits/',
        primaryPatternId: 'bit-manipulation',
        benchmarkTime: 10,
        acceptanceRate: 56.1,
        insight: 'Iterate 32 times, shifting the result and adding the last bit of n.',
      },
      {
        id: 'bm-5',
        title: 'Missing Number',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Bit Manipulation', 'Math'],
        url: 'https://leetcode.com/problems/missing-number/',
        primaryPatternId: 'bit-manipulation',
        benchmarkTime: 5,
        acceptanceRate: 64.2,
        insight: 'Use XOR with all numbers from 0 to n and all elements in the array.',
      },
      {
        id: 'bm-6',
        title: 'Power of Two',
        platform: 'leetcode',
        difficulty: 'Foundation',
        tags: ['Bit Manipulation', 'Math'],
        url: 'https://leetcode.com/problems/power-of-two/',
        primaryPatternId: 'bit-manipulation',
        benchmarkTime: 3,
        acceptanceRate: 46.5,
        insight: 'A power of two has exactly one bit set: n > 0 && (n & (n - 1)) == 0.',
      },
      {
        id: 'bm-7',
        title: 'Sum of Two Integers',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Bit Manipulation'],
        url: 'https://leetcode.com/problems/sum-of-two-integers/',
        primaryPatternId: 'bit-manipulation',
        benchmarkTime: 15,
        acceptanceRate: 51.2,
        insight: 'Use XOR for sum and AND-shift for carry: (a ^ b) and (a & b) << 1.',
      },
      {
        id: 'bm-8',
        title: 'Bitwise AND of Numbers Range',
        platform: 'leetcode',
        difficulty: 'Brain Burner',
        tags: ['Bit Manipulation'],
        url: 'https://leetcode.com/problems/bitwise-and-of-numbers-range/',
        primaryPatternId: 'bit-manipulation',
        benchmarkTime: 15,
        acceptanceRate: 43.1,
        insight: 'Find the common prefix of m and n by shifting them right until they match.',
      },
    ],
  },
];

export const masteryLists: MasteryList[] = [
  {
    id: 'arrays-mastery',
    title: 'Arrays Mastery',
    description: 'Master array manipulation and optimization techniques. Build solid foundations with problems covering sorting, searching, and manipulation.',
    problemCount: 10,
    estimatedDifficulty: 'Beginner to Intermediate',
    problems: patterns
      .flatMap((p) => p.problems)
      .filter((p) => p.tags.includes('Array'))
      .slice(0, 10),
  },
  {
    id: 'strings-core',
    title: 'Strings Core Pack',
    description: 'Essential string manipulation and pattern matching. Learn substring techniques, character encoding, and efficient string algorithms.',
    problemCount: 8,
    estimatedDifficulty: 'Beginner to Intermediate',
    problems: patterns
      .flatMap((p) => p.problems)
      .filter((p) => p.tags.includes('String'))
      .slice(0, 8),
  },
  {
    id: 'graphs-god-pack',
    title: 'Graphs God Pack',
    description: 'Comprehensive graph algorithms and traversal techniques. Master DFS, BFS, topological sort, and shortest path algorithms.',
    problemCount: 12,
    estimatedDifficulty: 'Intermediate to Advanced',
    problems: patterns.find((p) => p.id === 'graphs')?.problems || [],
  },
  {
    id: 'dp-advanced',
    title: 'Dynamic Programming Advanced',
    description: 'Advanced DP patterns and optimization. Understand state representation, transitions, and multi-dimensional DP.',
    problemCount: 8,
    estimatedDifficulty: 'Advanced',
    problems: patterns.find((p) => p.id === 'dynamic-programming')?.problems || [],
  },
  {
    id: 'ds-essentials',
    title: 'Data Structures Essentials',
    description: 'Master the core data structures: Linked Lists, Stacks, and Queues. Essential for any technical interview.',
    problemCount: 12,
    estimatedDifficulty: 'Beginner to Intermediate',
    problems: [
      ...(patterns.find((p) => p.id === 'linked-lists')?.problems || []),
      ...(patterns.find((p) => p.id === 'stacks-queues')?.problems || []),
    ],
  },
  {
    id: 'bit-ninja',
    title: 'Bit Manipulation Ninja',
    description: 'Master the art of bit manipulation. Learn to optimize space and solve problems with low-level bit operations.',
    problemCount: 8,
    estimatedDifficulty: 'Intermediate to Advanced',
    problems: patterns.find((p) => p.id === 'bit-manipulation')?.problems || [],
  },
  {
    id: 'backtracking-master',
    title: 'Backtracking Master',
    description: 'Comprehensive guide to recursion and backtracking. Solve complex puzzles and combinatorial problems.',
    problemCount: 10,
    estimatedDifficulty: 'Intermediate to Advanced',
    problems: patterns.find((p) => p.id === 'recursion-backtracking')?.problems || [],
  },
];
